In [3]:
#create 1D array of numbers from 10 to 50.
import numpy as np
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [2]:
#Create a 3x3 array of random numbers between 0 and 1.
ran_ar=np.random.random((3,3))
print(ran_ar)

[[0.97182172 0.04660148 0.60391593]
 [0.57216666 0.80330195 0.80900431]
 [0.95160896 0.12463879 0.82892791]]


In [3]:
#Find the shape,size,and data type of the array you created in the previous task.
print("Shape:",ran_ar.shape)
print("Size:",ran_ar.size)
print("DataType:",ran_ar.dtype)

Shape: (3, 3)
Size: 9
DataType: float64


In [5]:
#Add 5 to every element of a 1D array.
ar1=np.array([1,2,3])
print(ar1+5)


[6 7 8]


In [6]:
#Multiply two 2D arrays element-wise.
ar2=np.array([[1,2],[3,4]])
ar3=np.array([[5,6],[7,8]])
res=np.dot(ar2,ar3)
print(res)

[[19 22]
 [43 50]]


In [7]:
#Create a 5x5 array of integers from 1 to 25.
a1=np.arange(1,26).reshape(5,5)
print(a1)
#Extract first row.
print("First row:",a1[0,:])
#Extract last column
print("Last column:",a1[:,4])
#A subarray of the first three rows and first two columns.
print("Subarray:",a1[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray: [[ 1  2]
 [ 6  7]
 [11 12]]


In [8]:
#Create a 5x5 array of integers from 1 to 25.
a1=np.arange(1,26).reshape(5,5)
print(a1)
#Extract first row.
print("First row:",a1[0,:])
#Extract last column
print("Last column:",a1[:,4])
#A subarray of the first three rows and first two columns.
print("Subarray:",a1[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray: [[ 1  2]
 [ 6  7]
 [11 12]]


In [9]:
#Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
arr=np.arange(1,13)
arr=arr.reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#Create a 3x3 matrix of ones.Add a 1D array to each row.
a=np.ones((3,3))
print(a)
a1=np.array([1,2,3])
print(a+a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [11]:
#Create 1D array of random integers between 1 and 50.Extract all elements that are divisible by 5.
arr=np.random.randint(1,50,size=10)
print(arr)
div_5=arr[arr%5==0]
print(div_5)

[38 48  3 38 19 15 33 33 31 43]
[15]


In [12]:
#Create two 2x2 matrices and perform matrix multiplication.
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
print(mat1.dot(mat2))

[[19 22]
 [43 50]]


In [13]:
#Given a 4x4 array,use fancy indexing to extract the diagonal elements.
ar=np.arange(1,17).reshape(4,4)
print(ar)
diag=ar[np.arange(4),np.arange(4)]
print(diag)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
